version: '3.9'

services:
  springboot:
    image: kimjinbum/simhae-springboot:latest
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://${{ secrets.RDS_ENDPOINT }}:5432/postgres
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}