version: '3.9'

services:
  springboot:
    image: kimjinbum/simhae-springboot:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/simhae?serverTimezone=Asia/Seoul&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      DEPLOY_FASTAPI_URL: "fastapi:8000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true