version: '3.9'

services:
  springboot:
    image: kimjinbum/simhae-springboot:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RDS_ENDPOINT: ${RDS_ENDPOINT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
